klab-ilc-cnr/maia-fe

src/app/pages/workspace/workspace.component.ts, src/app/services/storage.service.ts
Added instance-dependent prefix to keys in storage. Optimized storage cleanup
=> Can't simultaneously access different instances of Maia

package-lock.json, package.json, src/app/controllers/editors/text-annotation-editor/text-annotation-editor.component.html, src/app/pages/workspace/workspace-lexicon-tile/workspace-lexicon-tile.component.html, src/app/pages/workspace/workspace-lexicon-tile/workspace-lexicon-tile.component.ts
Closes https://github.com/klab-ilc-cnr/Maia/issues/23
=> Enhancement lexicon explorer case insensitive search

package-lock.json, package.json, src/app/controllers/tab-controllers/tabs-lexical-entry/tabs-lexical-entry.component.html, src/app/controllers/tab-controllers/tabs-sense/tabs-sense.component.html, src/app/pages/workspace/workspace-lexicon-edit-tile/workspace-lexicon-edit-tile.component.html, src/app/pages/workspace/workspace-lexicon-edit-tile/workspace-lexicon-edit-tile.component.scss, src/app/pages/workspace/workspace-lexicon-edit-tile/workspace-lexicon-edit-tile.component.ts
Closes https://github.com/klab-ilc-cnr/Maia/issues/32
=> Bugfix/lexicon editor column too narrow https://github.com/klab-ilc-cnr/Maia/issues/32

src/app/pages/workspace/workspace-text-window/workspace-text-window.component.ts
=> 1 issue if annotated text is at the beginning of a line

src/app/models/tile/lexicon-edit-tile-content.model.ts, src/app/pages/workspace/workspace.component.ts
Closes https://github.com/klab-ilc-cnr/Maia/issues/80
=> 80 console message type lexicon edit not implemented

src/app/pages/workspace/workspace.component.ts
Closes https://github.com/klab-ilc-cnr/Maia/issues/95
=> Added DICTIONARY to tile management

src/app/pages/workspace/workspace-lexicon-tile/workspace-lexicon-tile.component.html, src/app/pages/workspace/workspace-lexicon-tile/workspace-lexicon-tile.component.scss, src/app/pages/workspace/workspace-lexicon-tile/workspace-lexicon-tile.component.ts, src/app/services/lexicon.service.ts, src/assets/i18n/en.json, src/assets/i18n/it.json
Closes https://github.com/klab-ilc-cnr/Maia/issues/97
=> Refactor of the insertion of a new lexical entry

package-lock.json, package.json, src/app/pages/workspace/workspace-text-window/workspace-text-window.component.html, src/app/pages/workspace/workspace-text-window/workspace-text-window.component.ts
questa pr comprende anche la risoluzione della  issue 110-unexpected-scrolling-of-the-text-window-when-clicking-an-annotation
https://github.com/klab-ilc-cnr/Maia/issues/110
=> 108 unintended scrolling on annotation saving

package-lock.json, package.json, src/app/models/texto/corpus-element.ts, src/app/pages/workspace/workspace-text-window/workspace-text-window.component.html, src/app/pages/workspace/workspace-text-window/workspace-text-window.component.ts
=> 102 double clic for text annotation should not select whitespaces following the selected word

package-lock.json, package.json, src/app/pages/workspace/workspace-corpus-explorer/workspace-corpus-explorer.component.html, src/app/pages/workspace/workspace-corpus-explorer/workspace-corpus-explorer.component.ts
Enhancement text uploader, splitline visible only if marked text is selected
=> 125 text uploader

package-lock.json, package.json, src/app/pages/workspace/workspace-corpus-explorer/workspace-corpus-explorer.component.ts
Fixed management of file name with dots, closes issue https://github.com/klab-ilc-cnr/Maia/issues/50
=> 50 uploaded files names are being cut after dot character

package-lock.json, package.json, src/app/pages/workspace/workspace-corpus-explorer/workspace-corpus-explorer.component.html, src/app/pages/workspace/workspace-corpus-explorer/workspace-corpus-explorer.component.scss
Fixed scrolling in Corpus Explorer https://github.com/klab-ilc-cnr/Maia/issues/53
=> 53 header of corpus explorer window should not scroll

package-lock.json, package.json, src/app/controllers/editors/text-annotation-editor/text-annotation-editor.component.ts, src/app/pages/workspace/workspace-text-window/workspace-text-window.component.scss, src/app/pages/workspace/workspace-text-window/workspace-text-window.component.ts, src/app/pages/workspace/workspace.component.ts
Questa da guardare dopo il merge della #197 per non vedere il codice ripetuto tra le modifiche
=> 111 loop of texto on layer selection

package-lock.json, package.json, src/app/controllers/editors/text-annotation-editor/text-annotation-editor.component.ts, src/app/pages/workspace/workspace-text-window/workspace-text-window.component.html, src/app/pages/workspace/workspace-text-window/workspace-text-window.component.scss, src/app/pages/workspace/workspace-text-window/workspace-text-window.component.ts, src/app/pages/workspace/workspace.component.ts
=> 114 modifica select pannello text

package-lock.json, package.json, src/app/controllers/editors/text-annotation-editor/text-annotation-editor.component.ts, src/app/pages/workspace/workspace-text-window/workspace-text-window.component.html, src/app/pages/workspace/workspace-text-window/workspace-text-window.component.ts, src/app/pipes/should-be-editable.pipe.ts
Ho fatto molte modifiche tra cui la gestione delle annotazioni e dei dati cachati, oltre che aver sistemato vari bug e migliorato lo scroller. Potrebbe sorgere qualche nuovo bug perciò se fate qualche test anche voi è meglio, in ogni caso penso sia un bel miglioramento sotto vari aspetti rispetto alla versione precedente a livello di user experience.
=> 117 refactor loaddata for cache issue

package-lock.json, package.json, src/app/pages/workspace/workspace-text-window/workspace-text-window.component.ts
Utilizzando take(1) sullo scroll dopo il primo scroll non veniva più aggiornato il recupero righe. Ho sostituito con takeUntil
=> Fixed subscribe takeuntil management

package-lock.json, package.json, src/app/forms/double-autocomplete/double-autocomplete.component.html, src/app/forms/double-autocomplete/double-autocomplete.component.ts
Fixes  https://github.com/klab-ilc-cnr/Maia/issues/78
=> Disabling relation field when value is selected

package-lock.json, package.json, src/app/controllers/editors/text-annotation-editor/text-annotation-editor.component.ts, src/app/pages/workspace/workspace-text-window/workspace-text-window.component.ts
Correzione della gestione della creazione e modifica delle feature di una annotazione. Fixes  https://github.com/klab-ilc-cnr/Maia/issues/139
=> Fix create update feature

package-lock.json, package.json, src/app/controllers/editors/dictionary-sorting-editor/dictionary-sorting-editor.component.html, src/app/controllers/editors/dictionary-sorting-editor/dictionary-sorting-editor.component.ts
Removed numeration from lemma in the sorting tree
=> Fix numeration in sorting tree

package-lock.json, package.json, src/app/models/search/search-result.ts, src/app/models/text/text-line.ts, src/app/pages/workspace/workspace-lexicon-edit-tile/workspace-lexicon-edit-tile.component.html, src/app/pages/workspace/workspace-lexicon-tile/workspace-lexicon-tile.component.html, src/app/pages/workspace/workspace-text-window/workspace-text-window.component.html, src/app/pages/workspace/workspace-text-window/workspace-text-window.component.ts, src/app/pages/workspace/workspace.component.ts, src/assets/i18n/en.json, src/assets/i18n/it.json
Added no definition message to Lexicon Explorer and Editor
=> 150 no definition message

package-lock.json, package.json, src/app/controllers/editors/form-core-editor/form-core-editor.component.html, src/app/controllers/editors/form-core-editor/form-core-editor.component.ts, src/app/controllers/editors/sense-core-editor/sense-core-editor.component.html, src/app/controllers/editors/sense-core-editor/sense-core-editor.component.ts, src/app/controllers/tab-controllers/tabs-form/tabs-form.component.html, src/app/controllers/tab-controllers/tabs-form/tabs-form.component.ts, src/app/controllers/tab-controllers/tabs-sense/tabs-sense.component.html, src/app/controllers/tab-controllers/tabs-sense/tabs-sense.component.ts, src/styles.scss
Closes https://github.com/klab-ilc-cnr/Maia/issues/151
=> Mod representation and definitions behavior

package-lock.json, package.json, src/app/controllers/editors/text-annotation-editor/text-annotation-editor.component.ts, src/app/forms/generic-autocomplete/generic-autocomplete.component.ts
Fixes https://github.com/klab-ilc-cnr/Maia/issues/154
=> Fix clear button in annotation for lexical features

package-lock.json, package.json, src/app/controllers/editors/form-core-editor/form-core-editor.component.html, src/app/controllers/editors/form-core-editor/form-core-editor.component.ts, src/app/controllers/editors/sense-core-editor/sense-core-editor.component.html, src/app/controllers/editors/sense-core-editor/sense-core-editor.component.ts, src/app/pages/workspace/workspace-text-window/workspace-text-window.component.ts, src/assets/i18n/en.json, src/assets/i18n/it.json
Added update/delete management for definitions and representations. Fixes issue https://github.com/klab-ilc-cnr/Maia/issues/152
Internazionalized sense and form core editors strings
=> 152 update management for strings

package-lock.json, package.json, src/app/controllers/editors/lex-entity-relations/lex-entity-semantic-rel-indirect/lex-entity-semantic-rel-indirect.component.html, src/app/controllers/editors/lex-entity-relations/lex-entity-semantic-rel/lex-entity-semantic-rel.component.html, src/app/forms/generic-autocomplete/generic-autocomplete.component.html
Handling a high number of options in autocomplete type fields, closes issue https://github.com/klab-ilc-cnr/Maia/issues/159
=> Handling a high number of options in autocomplete type fields

package-lock.json, package.json, src/app/controllers/editors/dictionary-entry-full-editor/dictionary-entry-full-editor.component.html
set etymon field to italic, closes https://github.com/klab-ilc-cnr/Maia/issues/166
=> 166 italic for etymon

README.md, package-lock.json, package.json, src/app/app.module.ts, src/app/controllers/editors/lex-entry-decomp/lex-entry-decomp.component.html, src/app/controllers/editors/lex-entry-decomp/lex-entry-decomp.component.scss, src/app/controllers/editors/lex-entry-decomp/lex-entry-decomp.component.spec.ts, src/app/controllers/editors/lex-entry-decomp/lex-entry-decomp.component.ts, src/app/controllers/tab-controllers/tabs-lexical-entry/tabs-lexical-entry.component.html, src/app/controllers/tab-controllers/tabs-lexical-entry/tabs-lexical-entry.component.ts, src/app/forms/autocomplete-checkbox/autocomplete-checkbox.component.html, src/app/forms/autocomplete-checkbox/autocomplete-checkbox.component.ts, src/app/pages/usersManagement/user-form/user-form.component.html, src/app/services/lexicon.service.ts
Added Decomp panel in Lexicon to manage multiword
=> Enhancement decomp

package-lock.json, package.json, src/app/pages/workspace/workspace-lexicon-tile/workspace-lexicon-tile.component.html, src/app/pages/workspace/workspace-lexicon-tile/workspace-lexicon-tile.component.ts, src/app/services/global-state.service.ts, src/app/services/lexicon.service.ts
Changing in Lexicon Explorer, closes issues https://github.com/klab-ilc-cnr/Maia/issues/178 https://github.com/klab-ilc-cnr/Maia/issues/179 and https://github.com/klab-ilc-cnr/Maia/issues/180
=> Fix lexicon explorer

package-lock.json, package.json, src/app/models/custom-models/dictionary-note-vocabo.ts
Correzione del json parse in caso di campo note di una dictionary entry vuoto
=> fixed json parse for empty note

src/app/controllers/editors/form-metadata-editor/form-metadata-editor.component.ts, src/app/controllers/editors/lex-entry-metadata-editor/lex-entry-metadata-editor.component.ts, src/app/controllers/editors/sense-metadata-editor/sense-metadata-editor.component.ts, src/app/controllers/tab-controllers/tabs-lexical-entry/tabs-lexical-entry.component.html
Closes issue https://github.com/klab-ilc-cnr/Maia/issues/187
=> Added delete relation to metadata tab in lexicon editor

package-lock.json, package.json, src/app/controllers/editors/form-core-editor/form-core-editor.component.html, src/app/controllers/editors/form-core-editor/form-core-editor.component.ts, src/app/controllers/editors/lex-entry-editor/lex-entry-editor.component.html, src/app/controllers/editors/lex-entry-editor/lex-entry-editor.component.ts, src/app/forms/double-autocomplete/double-autocomplete.component.html, src/app/forms/double-autocomplete/double-autocomplete.component.ts
Added morphology to lexical entry editor and inherited morphology to form editor. Closes issue https://github.com/klab-ilc-cnr/Maia/issues/176
=> 176 add morph traits to lexical entry

package-lock.json, package.json, src/app/controllers/editors/dictionary-entry-full-editor/dictionary-entry-full-editor.component.ts, src/app/controllers/editors/lex-entry-decomp/lex-entry-decomp.component.ts, src/app/controllers/editors/lex-entry-editor/lex-entry-editor.component.ts, src/app/controllers/editors/lex-entry-relations-editor/lex-entry-relations-editor.component.html, src/app/controllers/editors/text-annotation-editor/text-annotation-editor.component.html, src/app/controllers/editors/text-annotation-editor/text-annotation-editor.component.ts, src/app/forms/autocomplete-checkbox/autocomplete-checkbox.component.html, src/app/forms/autocomplete-checkbox/autocomplete-checkbox.component.ts, src/app/models/lexicon/lexical-entry.model.ts
Closes https://github.com/klab-ilc-cnr/Maia/issues/190
=> 190 add pos to component

package-lock.json, package.json, src/app/controllers/editors/dictionary-preview/dictionary-preview.component.html, src/app/controllers/editors/dictionary-preview/dictionary-preview.component.ts
(cherry picked from commit 7712d1ff251a48325aec019608339ede7f08ec10)
=> 191-unexpected-scrollig-on-change-table-page

package-lock.json, package.json, src/app/pages/workspace/workspace-search-tile/workspace-search-tile.component.ts
=> 203 remove selection after multiple annotatio or delete

package-lock.json, package.json, src/app/controllers/editors/form-core-editor/form-core-editor.component.ts, src/app/controllers/editors/sense-core-editor/sense-core-editor.component.ts, src/app/pages/workspace/workspace-lexicon-tile/workspace-lexicon-tile.component.ts
Fix error messages for elements already used in annotation
=> Fixed error message for already annotated elements
